[project]
org-name = "jeradrutnam"
version = "0.1.0"
license = "Apache License 2.0"
authors = ["jeradrutnam"]
repository = "https://github.com/jeradrutnam/boxen"
keywords = ["boxen", "box", "boxes", "terminal", "console", "ansi"]